### ISSUE TITLE
When i have trained 15 epochs, CIDEr always is 0.001,I do not know how to resolve this problem. can you help me?

### ISSUE THREAD

**Issue by songchuanle-1** [CrossmodalGroup/ER-SAN#2]
image 275025: woods frames snout tulip caught dinosaurs woods peek
evaluating validation preformance... 4979/5000 (1.840761)
image 362971: woods golden ended union woods resemble china tablets
image 474: woods climber benched tulip musical draining bringing cooking launching
image 49327: woods hanging scraper woods sealed interviewed woods foreheads
image 144959: woods silver woody elegantly bringing crossroads honk bringing woods goofing
image 349414: woods hanging rice dinosaurs nicely china woods arrow bringing woods goofing
image 143359: woods hanging climate off cooking rags rich scraper woods sealed
image 546658: woods hanging rice dinosaurs cooking interstate service woods cafe
image 200563: woods hanging scraper woods cafe interviewed woods interstate sunroof successful
image 345469: woods guy pretending dinosaurs woods teddy sorted woody fisherman china knit
image 306619: woods majestically dinosaurs telescope gallops bundt woods buying door
evaluating validation preformance... 4989/5000 (1.860643)
image 324313: woods holds woody woods seating feels honk bringing retrieve china crossroads
image 46616: minnie memorial rice dozen stern woods peep bringing woods gain
image 285832: woods heavy starring woody woods leather parrots caddy want woods goofing
image 496718: woods climber benched musical woods overgrowth gains dinosaurs woods heavy starring
image 398209: woods heavy starring woody woods predators want woods goofing
image 568041: woods heavy starring woody woods telescope caddy want woods goofing woody horizontal
image 206596: woods climber singer catchers woods draining buddhist bringing woods peek
image 451949: minnie lipstick woody tightly pecking bog roadway woods mirrors
image 203138: woods hanging want woods patch benched rice dinosaurs nicely china woods fit
image 296759: minnie burrito storefronts queue born dinosaurs ribbons want address
evaluating validation preformance... -1/5000 (1.820787)
loading annotations into memory...
0:00:00.119141
creating index...
index created!
using 5000/5000 predictions
Loading and preparing results...     
DONE (t=0.02s)
creating index...
index created!
tokenization...
E:\song\ER-SAN-main\pycocoevalcap\tokenizer E:\song\ER-SAN-main\pycocoevalcap\tokenizer\tmph3xikfjn
PTBTokenizer tokenized 307821 tokens at 2790538.92 tokens per second.
E:\song\ER-SAN-main\pycocoevalcap\tokenizer E:\song\ER-SAN-main\pycocoevalcap\tokenizer\tmpht6d5wp0
PTBTokenizer tokenized 53842 tokens at 850787.47 tokens per second.
setting up scorers...
computing Bleu score...
{'testlen': 48843, 'reflen': 48341, 'guess': [48843, 43843, 38843, 33843], 'correct': [106, 0, 0, 0]}
ratio: 1.010384559690511
Bleu_1: 0.002
Bleu_2: 0.000
Bleu_3: 0.000
Bleu_4: 0.000
computing METEOR score...
METEOR: 0.010
computing Rouge score...
ROUGE_L: 0.002
computing CIDEr score...
CIDEr: 0.001
computing SPICE score...
Parsing reference captions
Initiating Stanford parsing pipeline
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
[main] INFO edu.stanford.nlp.pipeline.TokenizerAnnotator - TokenizerAnnotator: No tokenizer type provided. Defaulting to PTBTokenizer.
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
[main] INFO edu.stanford.nlp.parser.common.ParserGrammar - Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... 
done [0.2 sec].
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
[main] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [0.6 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.3 sec].
Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.3 sec].
Threads( StanfordCoreNLP ) [25.998 seconds]
Threads( StanfordCoreNLP ) [23.241 seconds]
Threads( StanfordCoreNLP ) [11.351 seconds]
Parsing test captions
Threads( StanfordCoreNLP ) [13.569 seconds]
SPICE evaluation took: 1.350 min
SPICE: 0.003
model saved to log_transformer_triplet\model.pth
Read data: 0.0279085636138916
iter 186000 (epoch 16), train_loss = 1.558, time/batch = 0.310
Read data: 0.030405282974243164
iter 186001 (epoch 16), train_loss = 1.423, time/batch = 0.086
Read data: 0.026419639587402344

**Comment by moon4869** [comment]
I have the same problem and don't know why

> computing Bleu score...
> {'testlen': 46876, 'reflen': 46898, 'guess': [46876, 41876, 36876, 31876], 'correct': [85, 0, 0, 0]}
> ratio: 0.9995308968399292
> Bleu_1: 0.002
> Bleu_2: 0.000
> Bleu_3: 0.000
> Bleu_4: 0.000
> computing METEOR score...
> METEOR: 0.008
> computing Rouge score...
> ROUGE_L: 0.002
> computing CIDEr score...
> CIDEr: 0.001
